targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/src/presentation/screens/**
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/src/presentation/navigation/**