name: real8_wallet
description: A Stellar wallet for REAL8 token
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  stellar_dart: ^0.8.0
  flutter_secure_storage: ^9.0.0
  dio: ^5.0.0
  flutter_bloc: ^8.0.0
  intl: ^0.19.0
  go_router: ^14.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/flag_en.png
    - assets/images/flag_es.png
